.PHONY: start_dev
start_dev:  ## Start the dev container
	docker-compose --env-file ../docker-compose.env -f ../docker-compose.yml up

.PHONY: stop_dev
stop_dev:  ## Stop the dev container 
	docker-compose --env-file ../docker-compose.env -f ../docker-compose.yml down
