version: "3.9"

services:
  client:
    image: refinebio-client-dev 
    ports: 
     - ${CLIENT_PORT}:${CLIENT_PORT}
    build: 
      context: ./client
      dockerfile: Dockerfile
    command: > 
      bash -c 'cd /app &&
             yarn && 
             yarn dev -p ${CLIENT_PORT}'
    volumes:
      - ./client:/app

