version: "3.9"

services:
  client:
    image: refinebio-web
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c 'cd /app &&
             yarn install --frozen-lockfile && 
             yarn dev -p ${CLIENT_PORT}'
    volumes:
      - ./:/app
