version: "3.9"

services:
  client:
    image: refinebio-web
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
      - ${STORYBOOK_PORT}:${STORYBOOK_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c 'cd /app &&
             yarn && 
             (yarn storybook --quiet -p ${STORYBOOK_PORT} &
              yarn dev -p ${CLIENT_PORT})'
    volumes:
      - ./:/app
