version: "3.9"

services:
  client:
    image: refinebio-web
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      STAGE_API_HOST: ${STAGE_API_HOST}
      STAGE_API_VERSION: ${STAGE_API_VERSION}
      STAGE_HUBSPOT_ACCESS_TOKEN: ${STAGE_HUBSPOT_ACCESS_TOKEN}
      STAGE_SENTRY_ENV: ${STAGE_SENTRY_ENV}
      STAGE_SENTRY_DSN: ${STAGE_SENTRY_DSN}
      STAGE_SLACK_HOOK_URL: ${STAGE_SLACK_HOOK_URL}
      STAGE_GITHUB_TOKEN: ${STAGE_GITHUB_TOKEN}
      STAGE_GITHUB_ENDPOINT: ${STAGE_GITHUB_ENDPOINT}
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    command: >
      bash -c 'cd /app && yarn dev -p ${CLIENT_PORT}'
    volumes:
      - ./:/app
  storybook:
      image: refinebio-web-storybook
      ports:
        - ${STORYBOOK_PORT}:${STORYBOOK_PORT}
      build:
        context: .
        dockerfile: Dockerfile
        target: local
      command: >
        bash -c 'cd /app &&
                 yarn install &&
                 yarn storybook --quiet -p ${STORYBOOK_PORT}'
      volumes:
        - ./:/app  
